### ISSUE TITLE
Move / merge TarballUtil into FileIOUtils (PowerSystemUtils)

### ISSUE THREAD

**Issue by ckittl** [ie3-institute/PowerSystemDataModel#234]
... as they are partially duplicates and would benefit from a joint implementation.

**Comment by ckittl** [comment]
- [ ] Revise `TarballUtils`
- [ ] Mark `TarballUtils` as Deprecated
- [ ] Give a hint in JavaDoc to use the `FileIOUtils`
- [ ] Merge the zipping methods from `FileIOUtils` and `TarballUtils`

**Comment by ahamshubham** [comment]
@ckittl Is it possible to get more clarification on the first point (Revise TarballUtils)?

**Comment by ahamshubham** [comment]
I have analyzed the files FileIOUtils.java and TarballUtils.java in detail. I have several queries and comments after performing the analysis:

Compression:
A) As far as I have understood, in order to transfer the functionality of compressing files from FileIOUtils.java to TarballUtils.java, I need to transfer the functions named gzip in FileIOUtils.java to replace compress and checkAndCreateArchive functions in TarballUtils.java. I have noticed that while compressing files, TarballUtils.java has code for performing additional checks. These additional checks include checks like whether the output file already exists. So, if we merge the code from FileIOUtils.java, are we supposed to preserve these additional checks?

Extraction:
B ) The file TarballUtils.java has also several functions for unzipping an archive file. But, there are no functions for this purpose in FileIOUtils.java. Do we no longer need these functions in TarballUtils.java?

Other functions:
C) Do we need to transfer the functions for deleting files and getting BufferedWriter objects from FileIOUtils.java to TarballUtils.java?

Other comments / queries:
D) In the second gzip function in FileIOUtils.java, no checks are being performed for comparing input filename and output filename as mentioned in the comments. But, this function is called with the outputFileName variable having an empty string so there is no problem.

E) Also, in the function deleteRecursively in FileIOUtils.java, I do not understand one thing. If there is an IOException, as far as I think, the program will stop automatically, however, we have code which is trying to delete files and directories in case there is an IOException. Is the code redundant or am I mistaken?

F) In the function determineTargetDirectory in TarballUtils.java, the else if does not delete the contents of the targetDirectory in case an overwrite is requested. In case we need to keep this functionality, I think the contents of this if have to be modified.

**Comment by ahamshubham** [comment]
Comment from Chris: "First, and I think that'll resolve most of your questions: Our goal is to remove the TarballUtils from PowerSystemDataModel, as they are no longer specific for the data model, what they have been initially. Therefore, everything from TarballUtils should be moved and merged into FileIOUtils keeping the best parts of two worlds. So if TarballUtils has additional checks, keep them. If the methods in FileIOUtils have good routines keep them as well. For sure, we would like to have a reasonable naming for the new method, that get's created by merging TarballUtils#compress and FileIOUtils#zip.
An additional remark / request: Please don't just delete things you move. Please place an @Deprecated annotation and add a meaningful remark to the JavaDoc to be non-breaking as long as possible. The deprecated code then can be removed somewhen later, when nobody still uses it.

Regarding D): I'm afraid I don't fully get your point. What comments do you mean? Can you point me to some place in the code, where you refer to? Additionally, please notice, that we are talking about a library. So it might as well happen, that the second gzip is called in another project, though you might not see it from this point.
Regarding E): In general, the program does terminate with error code, if any uncaught Exception does occur. So if you know, what can go wrong and you know how you can "fix" it in runtime without user interaction, you might catch an occurring Exception and do what fixes it. I'm not fully sure to what you refer here as well, but I guess you refer to the places, where archive creation or extraction fails. In that cases, I just intend to tidy up (e.g. delete the incomplete extracted parts of the archive). But maybe you can point me to your place of doubt?
Regarding F): You are right. That part is missing. It worked every time for me, because I just only extracted the exact files, that yet are apparent. Anyways, @jhiry didn't feel well with my override flag as well. So as of now I would like to ask you to throw an FileAlreadyExistsException instead of just logging stuff. Then, as previously mentioned, the guy using the method is able to catch this exception, delete the directory or do something else and go ahead the way he or she needs it."

=>

D : Actually, I did not understand the comment section from line numbers 120 to 121 in FileIOUtils.java which talks about the parameter outputFileName. I understand that in the code, the parameter outputFileName, is being checked for whether it ends with ".gz". If it does, it is being used as the location for storing output file. If it does not, filename + ".gz" is used as the location for storing output file. However, I do not understand what the comment section from line numbers 120 to 121 means. Although, it is not a very crucial doubt.

E : Actually, I am referring to the function deleteRecursively in FileIOUtils.java. For example, in line numbers 217 and 233, we have an input parameter, exc (of type IOException), to the functions visitFileFailed and postVisitDirectory. This input parameter is also being used on Line Number 234. If I understand your comment here and the comment section from lines 224 to 225 correctly, I think this can be null or refer to an IOException which is being propagated. I was before under the impression that once an exception occurs, the execution of the program stops completely. That was a mistake in my understanding and I think I understand the code now.

**Comment by ckittl** [comment]
> D : Actually, I did not understand the comment section from line numbers 120 to 121 in FileIOUtils.java which talks about the parameter outputFileName. I understand that in the code, the parameter outputFileName, is being checked for whether it ends with ".gz". If it does, it is being used as the location for storing output file. If it does not, filename + ".gz" is used as the location for storing output file. However, I do not understand what the comment section from line numbers 120 to 121 means. Although, it is not a very crucial doubt.

This is just an additional option / fallback, if the parameters given are not correct. E.g. if you call `FileIOUtils.compress("test.txt", "blaFoo")`, the desired output file name is not valid, therefore falling back to creating a file called _test.txt.gz_. However, if you would like to have a different name for the file (e.g. calling `FileIOUtils.compress("test.txt", "compressedTest.gz"), then you get a _compressedTest.gz_ as output. Did this help?

An additional side note: As far as I get from the first glance, the code in `FileIOUtils` does something different than in `TarballUtils`. The latter one is capable to compress directories and puts everything into a tar archive before zipping it, while the first one only compresses one file without adding it to a tar archive before. Please take care of this difference when joining the code.

> E : Actually, I am referring to the function deleteRecursively in FileIOUtils.java. For example, in line numbers 217 and 233, we have an input parameter, exc (of type IOException), to the functions visitFileFailed and postVisitDirectory. This input parameter is also being used on Line Number 234. If I understand your comment here and the comment section from lines 224 to 225 correctly, I think this can be null or refer to an IOException which is being propagated. I was before under the impression that once an exception occurs, the execution of the program stops completely. That was a mistake in my understanding and I think I understand the code now.

Ah, okay! This "walking through the file tree" is implemented somewhat more clever. If it fails to visit a file, it catches the exception. And forwards it to the abstract `visitFileFailed` method to give power to the developer extending the abstract class in order to take care of handling the error. So, it is not propagated in the usual manner. As you cannot delete a non-empty directory, the error is propagated if you cannot visit a directory.

**Comment by ahamshubham** [comment]
Thank you. I understand.

**Comment by ahamshubham** [comment]
1) With the compress functions added in FileIOUtils.java, it is now possible to remove the gzip functions. But, I did not remove them because I felt that they might be in use already.
2) The TarballUtils functions throw an Exception named FileException. I have added the FileException code to the PowerSystemUtils in a similar way to how it was present in PowerSystemDataModel.
3) I have removed the override parameter from the determineTargetDirectory function and the extract function while adding them to FileIOUtils.java because it was not being used.
4) I have added deprecated tags and annotations to the TarballUtils.java file with additional comments indicating the changes to the functions.
