### ISSUE TITLE
Refactor ChpResult

### ISSUE THREAD

**Issue by baszach** [ie3-institute/PowerSystemDataModel#236]
The ChpResult class needs some slight changes to fit to the **refactored ChpModel** (e.g. consider the thermal power as a result)

**Comment by ahamshubham** [comment]
I have gone through the files `ChpInput.java` and `ChpResult.java` and I have several questions after my preliminary code study:
1) As far as I understand, `ChpInput.java` is used to represent a CHP plant by using several parameters. `ChpResult.java` on the other hand, I believe, is used to represent the output from a CHP plant. Is my understanding correct?
2) Apart from the parameter 'thermal power' being added to the `ChpResult.java` file, is there any other variable which is to be added?
3) Is there any model based on which we have defined the different parameters for a CHP plant in `ChpInput.java` and `ChpResult.java`?

**Comment by ckittl** [comment]
You analysed it correctly. The `ChpInput` is meant to be used to hold the static parameters of an existing chp plant, that later can be used in conjunction with an physical / mathematical model of the plant within a simulation. However, the simulation's result regarding the chp plant is meant to be expressed in `ChpResult`.

No, apart from that, nothing else has to be done. To be harmonized, please call it `qDot`.

No, as far as I know, it stems from reasoning about the inner structure of a simple, generic plant.

**Comment by ahamshubham** [comment]
Thank you, that was very helpful. I can see that in `ChpResult.java` there are two variables `p` and `q` being used which represent active and reactive power respectively and they are of type `ComparableQuantity<Power>`. I believe that in order to create the parameter `qDot` we can use the same type `ComparableQuantity<Power>` because the units of Thermal Power and Power are same or do we need to create a new type?

**Comment by ckittl** [comment]
Yes, that's fine.

Please consider extending `SystemParticipantResult` with the class `SystemParticipantWithHeatResult` and add the heat there. Then the `ChpResult` only has to extend `SystemParticipantWithHeatResult` instead of `SystemParticipantResult`. This is more flexible, as we don't have to do this task for the next results, that also comprise heat power.

**Comment by ahamshubham** [comment]
Okay sure. I will create a class named `SystemParticipantWithHeatResult`.

**Comment by ckittl** [comment]
I think this is of no major concern right now. But yes, you might refer to `StandardUnits#Q_DOT_RESULT`. In most cases in code it is preferable to use this static field.

**Comment by ahamshubham** [comment]
In `SystemParticipantResult.java`, I do not understand two things:
1) The docs before the function getQ() have text which goes like this: "Reactive power output of the decentralised energy resource asset. Convention: Generated powers are given in negative values.". I do not understand whether the same comment applies for the thermal power. I get that reactive power output will be considered negative if it is generated and positive if it is consumed. Is the same true for thermal power?
2) The purpose of the function: `hashCode()` and whether it is needed in `SystemParticipantWithHeatResult` class.
